"""initial domain schema

Revision ID: 51ed672e0612
Revises:
Create Date: 2026-06-07 18:52:24.598716
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "51ed672e0612"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chapters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "progress_key",
            sa.Enum("START", "QINGHE", "KAIFENG", "CURRENT", "UNRESTRICTED", name="progress_key"),
            nullable=False,
        ),
        sa.Column("progress_rank", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "progress_rank >= 0 AND progress_rank <= 100",
            name=op.f("ck_chapters_progress_rank_range"),
        ),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_chapters_sort_order_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapters")),
        sa.UniqueConstraint("sort_order", name=op.f("uq_chapters_sort_order")),
    )
    op.create_index(op.f("ix_chapters_progress_key"), "chapters", ["progress_key"], unique=False)
    op.create_index(op.f("ix_chapters_progress_rank"), "chapters", ["progress_rank"], unique=False)
    op.create_index(op.f("ix_chapters_slug"), "chapters", ["slug"], unique=True)
    op.create_table(
        "submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "submission_type",
            sa.Enum(
                "RELATIONSHIP", "EVENT", "INTERPRETATION", "CORRECTION", name="submission_type"
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("contact", sa.String(length=200), nullable=True),
        sa.Column("source_note", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="submission_status"),
            nullable=False,
        ),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
    )
    op.create_index(op.f("ix_submissions_status"), "submissions", ["status"], unique=False)
    op.create_index(
        op.f("ix_submissions_submission_type"), "submissions", ["submission_type"], unique=False
    )
    op.create_table(
        "factions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("faction_type", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("spoiler_level", sa.Integer(), nullable=False),
        sa.Column("visible_after_chapter_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="content_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "spoiler_level >= 0 AND spoiler_level <= 3",
            name=op.f("ck_factions_spoiler_level_range"),
        ),
        sa.ForeignKeyConstraint(
            ["visible_after_chapter_id"],
            ["chapters.id"],
            name=op.f("fk_factions_visible_after_chapter_id_chapters"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factions")),
    )
    op.create_index(op.f("ix_factions_name"), "factions", ["name"], unique=False)
    op.create_index(op.f("ix_factions_slug"), "factions", ["slug"], unique=True)
    op.create_index(op.f("ix_factions_status"), "factions", ["status"], unique=False)
    op.create_table(
        "story_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("impact", sa.Text(), nullable=True),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("spoiler_level", sa.Integer(), nullable=False),
        sa.Column("visible_after_chapter_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="content_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_story_events_sort_order_nonnegative")),
        sa.CheckConstraint(
            "spoiler_level >= 0 AND spoiler_level <= 3",
            name=op.f("ck_story_events_spoiler_level_range"),
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_story_events_chapter_id_chapters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["visible_after_chapter_id"],
            ["chapters.id"],
            name=op.f("fk_story_events_visible_after_chapter_id_chapters"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_events")),
        sa.UniqueConstraint("chapter_id", "sort_order", name=op.f("uq_story_events_chapter_id")),
    )
    op.create_index(
        op.f("ix_story_events_chapter_id"), "story_events", ["chapter_id"], unique=False
    )
    op.create_index(op.f("ix_story_events_slug"), "story_events", ["slug"], unique=True)
    op.create_index(op.f("ix_story_events_status"), "story_events", ["status"], unique=False)
    op.create_index(op.f("ix_story_events_title"), "story_events", ["title"], unique=False)
    op.create_table(
        "characters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("interpretation", sa.Text(), nullable=True),
        sa.Column("identity_tags", sa.JSON(), nullable=False),
        sa.Column("faction_id", sa.UUID(), nullable=True),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("spoiler_level", sa.Integer(), nullable=False),
        sa.Column("first_appear_chapter_id", sa.UUID(), nullable=True),
        sa.Column("visible_after_chapter_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="content_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "importance >= 1 AND importance <= 5", name=op.f("ck_characters_importance_range")
        ),
        sa.CheckConstraint(
            "spoiler_level >= 0 AND spoiler_level <= 3",
            name=op.f("ck_characters_spoiler_level_range"),
        ),
        sa.ForeignKeyConstraint(
            ["faction_id"],
            ["factions.id"],
            name=op.f("fk_characters_faction_id_factions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["first_appear_chapter_id"],
            ["chapters.id"],
            name=op.f("fk_characters_first_appear_chapter_id_chapters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["visible_after_chapter_id"],
            ["chapters.id"],
            name=op.f("fk_characters_visible_after_chapter_id_chapters"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characters")),
    )
    op.create_index(op.f("ix_characters_faction_id"), "characters", ["faction_id"], unique=False)
    op.create_index(
        op.f("ix_characters_first_appear_chapter_id"),
        "characters",
        ["first_appear_chapter_id"],
        unique=False,
    )
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)
    op.create_index(op.f("ix_characters_slug"), "characters", ["slug"], unique=True)
    op.create_index(op.f("ix_characters_status"), "characters", ["status"], unique=False)
    op.create_table(
        "event_factions",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("faction_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["story_events.id"],
            name=op.f("fk_event_factions_event_id_story_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["faction_id"],
            ["factions.id"],
            name=op.f("fk_event_factions_faction_id_factions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "faction_id", name=op.f("pk_event_factions")),
    )
    op.create_table(
        "character_aliases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_aliases_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_aliases")),
        sa.UniqueConstraint(
            "character_id", "alias", name=op.f("uq_character_aliases_character_id")
        ),
    )
    op.create_index(
        op.f("ix_character_aliases_alias"), "character_aliases", ["alias"], unique=False
    )
    op.create_index(
        op.f("ix_character_aliases_character_id"),
        "character_aliases",
        ["character_id"],
        unique=False,
    )
    op.create_table(
        "event_characters",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_event_characters_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["story_events.id"],
            name=op.f("fk_event_characters_event_id_story_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "character_id", name=op.f("pk_event_characters")),
    )
    op.create_table(
        "relationships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_character_id", sa.UUID(), nullable=False),
        sa.Column("target_character_id", sa.UUID(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "MENTOR",
                "FAMILY",
                "ENEMY",
                "ALLY",
                "OLD_ACQUAINTANCE",
                "EXPLOITATION",
                "HIERARCHY",
                "SAME_SECT",
                "INTEREST",
                "HIDDEN",
                name="relation_type",
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("stage", sa.String(length=120), nullable=True),
        sa.Column("is_directional", sa.Boolean(), nullable=False),
        sa.Column("chapter_id", sa.UUID(), nullable=True),
        sa.Column("visible_after_chapter_id", sa.UUID(), nullable=True),
        sa.Column("spoiler_level", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="content_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_relationships_confidence_range")
        ),
        sa.CheckConstraint(
            "source_character_id <> target_character_id",
            name=op.f("ck_relationships_different_characters"),
        ),
        sa.CheckConstraint(
            "spoiler_level >= 0 AND spoiler_level <= 3",
            name=op.f("ck_relationships_spoiler_level_range"),
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_relationships_chapter_id_chapters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_character_id"],
            ["characters.id"],
            name=op.f("fk_relationships_source_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_character_id"],
            ["characters.id"],
            name=op.f("fk_relationships_target_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["visible_after_chapter_id"],
            ["chapters.id"],
            name=op.f("fk_relationships_visible_after_chapter_id_chapters"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships")),
        sa.UniqueConstraint(
            "source_character_id",
            "target_character_id",
            "relation_type",
            "chapter_id",
            name="uq_relationship_identity",
        ),
    )
    op.create_index(
        "ix_relationship_endpoints",
        "relationships",
        ["source_character_id", "target_character_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relationships_chapter_id"), "relationships", ["chapter_id"], unique=False
    )
    op.create_index(
        op.f("ix_relationships_relation_type"), "relationships", ["relation_type"], unique=False
    )
    op.create_index(
        op.f("ix_relationships_source_character_id"),
        "relationships",
        ["source_character_id"],
        unique=False,
    )
    op.create_index(op.f("ix_relationships_status"), "relationships", ["status"], unique=False)
    op.create_index(
        op.f("ix_relationships_target_character_id"),
        "relationships",
        ["target_character_id"],
        unique=False,
    )
    op.create_table(
        "relationship_events",
        sa.Column("relationship_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["story_events.id"],
            name=op.f("fk_relationship_events_event_id_story_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["relationship_id"],
            ["relationships.id"],
            name=op.f("fk_relationship_events_relationship_id_relationships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("relationship_id", "event_id", name=op.f("pk_relationship_events")),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "PLAYER_NOTE",
                "QUEST_REFERENCE",
                "OFFICIAL_REFERENCE",
                "COMMUNITY_ANALYSIS",
                name="source_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("reference", sa.String(length=500), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("character_id", sa.UUID(), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("relationship_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(character_id, event_id, relationship_id) = 1",
            name=op.f("ck_sources_exactly_one_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_sources_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["story_events.id"],
            name=op.f("fk_sources_event_id_story_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["relationship_id"],
            ["relationships.id"],
            name=op.f("fk_sources_relationship_id_relationships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_index(op.f("ix_sources_character_id"), "sources", ["character_id"], unique=False)
    op.create_index(op.f("ix_sources_event_id"), "sources", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_sources_relationship_id"), "sources", ["relationship_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sources_relationship_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_event_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_character_id"), table_name="sources")
    op.drop_table("sources")
    op.drop_table("relationship_events")
    op.drop_index(op.f("ix_relationships_target_character_id"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_status"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_source_character_id"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_relation_type"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_chapter_id"), table_name="relationships")
    op.drop_index("ix_relationship_endpoints", table_name="relationships")
    op.drop_table("relationships")
    op.drop_table("event_characters")
    op.drop_index(op.f("ix_character_aliases_character_id"), table_name="character_aliases")
    op.drop_index(op.f("ix_character_aliases_alias"), table_name="character_aliases")
    op.drop_table("character_aliases")
    op.drop_table("event_factions")
    op.drop_index(op.f("ix_characters_status"), table_name="characters")
    op.drop_index(op.f("ix_characters_slug"), table_name="characters")
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_index(op.f("ix_characters_first_appear_chapter_id"), table_name="characters")
    op.drop_index(op.f("ix_characters_faction_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_story_events_title"), table_name="story_events")
    op.drop_index(op.f("ix_story_events_status"), table_name="story_events")
    op.drop_index(op.f("ix_story_events_slug"), table_name="story_events")
    op.drop_index(op.f("ix_story_events_chapter_id"), table_name="story_events")
    op.drop_table("story_events")
    op.drop_index(op.f("ix_factions_status"), table_name="factions")
    op.drop_index(op.f("ix_factions_slug"), table_name="factions")
    op.drop_index(op.f("ix_factions_name"), table_name="factions")
    op.drop_table("factions")
    op.drop_index(op.f("ix_submissions_submission_type"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_status"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_chapters_slug"), table_name="chapters")
    op.drop_index(op.f("ix_chapters_progress_rank"), table_name="chapters")
    op.drop_index(op.f("ix_chapters_progress_key"), table_name="chapters")
    op.drop_table("chapters")
    op.execute("DROP TYPE IF EXISTS source_type")
    op.execute("DROP TYPE IF EXISTS relation_type")
    op.execute("DROP TYPE IF EXISTS content_status")
    op.execute("DROP TYPE IF EXISTS submission_status")
    op.execute("DROP TYPE IF EXISTS submission_type")
    op.execute("DROP TYPE IF EXISTS progress_key")
    # ### end Alembic commands ###
