/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_api_v1_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiResponse[GraphData] */
        ApiResponse_GraphData_: {
            data?: components["schemas"]["GraphData"] | null;
            error?: components["schemas"]["ErrorDetail"] | null;
            meta?: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[HealthData] */
        ApiResponse_HealthData_: {
            data?: components["schemas"]["HealthData"] | null;
            error?: components["schemas"]["ErrorDetail"] | null;
            meta?: components["schemas"]["ResponseMeta"];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Fields */
            fields?: {
                [key: string]: string[];
            } | null;
        };
        /** GraphData */
        GraphData: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            progress: components["schemas"]["ProgressKey"];
        };
        /** GraphEdge */
        GraphEdge: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source
             * Format: uuid
             */
            source: string;
            /**
             * Target
             * Format: uuid
             */
            target: string;
            relation_type: components["schemas"]["RelationType"];
            /** Label */
            label: string;
            /** Summary */
            summary: string;
            /** Directional */
            directional: boolean;
        };
        /** GraphNode */
        GraphNode: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Label */
            label: string;
            /** Faction Id */
            faction_id: string | null;
            /** Faction Name */
            faction_name: string | null;
            /** Importance */
            importance: number;
            /** Summary */
            summary: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
        };
        /**
         * ProgressKey
         * @enum {string}
         */
        ProgressKey: "start" | "qinghe" | "kaifeng" | "current" | "unrestricted";
        /**
         * RelationType
         * @enum {string}
         */
        RelationType: "mentor" | "family" | "enemy" | "ally" | "old_acquaintance" | "exploitation" | "hierarchy" | "same_sect" | "interest" | "hidden";
        /** ResponseMeta */
        ResponseMeta: {
            /** Request Id */
            request_id?: string | null;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_HealthData_"];
                };
            };
        };
    };
    get_graph_api_v1_graph_get: {
        parameters: {
            query?: {
                progress?: components["schemas"]["ProgressKey"];
                chapter?: string | null;
                faction?: string | null;
                relation_type?: components["schemas"]["RelationType"] | null;
                focus?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_GraphData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
